[package]
name = "producer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = "0.36.2"
testcontainers = { version = "0.15.0", feature = "postgres" }
testcontainers-modules = {version = "0.3.1"}
tokio = { version = "1.35.1", features = ["full"] }
postgres = "0.19.7"
