[package]
name = "producer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = "0.36.2"
testcontainers = "0.15.0"
tokio = { version = "1.35.1", features = ["full"] }

[dev-dependencies]
testcontainers = "0.15.0"
